# Generated by Django 3.0.2 on 2020-01-15 12:31

from django.db import migrations, models
import joining.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('profile_image', models.ImageField(upload_to=joining.models.get_image_path)),
                ('date', models.DateField(auto_now_add=True)),
                ('aadhar_number', models.IntegerField(unique=True)),
                ('aadhar_image', models.ImageField(upload_to=joining.models.get_image_path)),
                ('about', models.CharField(max_length=250)),
            ],
        ),
    ]
